version: '3'
services:
  api:
    image: sample-express-app
    build: .
    networks:
      - backend
    ports:
      - "3000:80"

  web-cli:
    image: sample-express-app
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge